


import "./globals.css";
// import {Inter} from "next/font/google"
import { Poppins } from "next/font/google";


// const InterFont = Inter({
//   subsets : ["latin"]
// })


const PoppinsFonts = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${PoppinsFonts.className} antialiased`}>{children}</body>
      
    </html>
  );
}
