import BottomMenu from "@/BottomMenu/BottomMenu";
import "./globals.css";
// import {Inter} from "next/font/google"
import { Poppins } from "next/font/google";
import Footer from "@/Footer/Footer";
import Home4 from "@/Home/Home4";

// const InterFont = Inter({
//   subsets : ["latin"]
// })

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {/* <Navbar /> */}
        <div className="mt-[5rem]">
          {children}
          <Home4 />
          <Footer />
          <BottomMenu />
        </div>
      </body>
    </html>
  );
}
