import BottomMenu from "@/BottomMenu/BottomMenu";
import "./globals.css";
import { Inter } from "next/font/google";
// import { Instrument_Sans } from "next/font/google";
import Footer from "@/Footer/Footer";
// import Home4 from "@/Home/Home4";

const InterFont = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Qviple",
  description: "Generated by create next app",
  icons: {
    icon: "/qvipleFavIcon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${InterFont.className} antialiased`}>
        {/* <Navbar /> */}
        <div className="mt-[5rem]">
          {children}
          {/* <Home4 /> */}
          <Footer />
          <BottomMenu />
        </div>
      </body>
    </html>
  );
}
